baseURL : "https://example.com"
languageCode : "en"
DefaultContentLanguage : "en"
title : "Tutorial Site"
theme : "anatole"
summarylength : 50
enableRobotsTXT : true

params:
  title : "I'm Jane Doe"
  author : "Jane Doe"
  copyright : "2020-2021"
  description : "Call me Jane"
  profilePicture : "profile.png"
  keywords : ""
  favicon : "favicons/"
  # example ["css/custom.css"]
  customCss : []
  # example ["js/custom.js"]
  customJs : []
  mainSections : ["blog"]
  images : ["featured-image.png"]
  doNotLoadAnimations : false
  postSectionName : "blog"
  # displayMode: "dark"

  ## Social links
  # use 'fab' when brand icons, use 'fas' when standard solid icons.
  socialIcons:
    - icon : "fab fa-linkedin"
      title : "Linkedin"
      url : "https://linkedin.com/"
    - icon : "fab fa-github"
      title : "GitHub"
      url : "https://github.com/lxndrblz/anatole/"
    - icon : "fab fa-instagram"
      title : "instagram"
      url : "https://www.instagram.com/"
    - icon : "fas fa-envelope"
      title : "e-mail"
      url : "mailto:mail@example.com"

  # Form Spree Contact Form
  #contactFormAction : "https://formspree.io/f/your-form-hash-here"
  # Google Site Verify
  #googleSiteVerify : "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  # indexDateFormat : "Mon, Jan 2, 2006"
  # listDateFormat : "Jan 2"
  # singleDateFormat : "Mon, Jan 2, 2006"
  # Commento Comments
  # CommentoURL : "https://commento.example.com/js/commento.js"
  # Read More links for truncated summaries
  # readMore : true

  ## Math settings
  math:
    enable : false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
    use : "katex"  # options: "katex", "mathjax". default is "katex".

## Menu items
menu:
  main:
    - name : "Home"
      identifier : "home"
      weight : 100
      url : "/"
    - name : "Posts"
      weight : 200
      identifier : "posts"
      url : "/post/"
    - name : "About"
      weight : 300
      identifier : "about"
      url : "/about/"
    - name : "Contact"
      weight : 400
      identifier : "contact"
      url : "/contact/"

taxonomies:
  category: categories
  series: series
  tag: tags

timeout: 30000

minify:
  disableXML: true
  minifyOutput: false

# Enable Disqus
#disqusShortname : ""

# Google Analytics
# Hugo supports GA4 V8.20 (latest at the time of writing) onwards.
#googleAnalytics : "UA-123-45"

# Syntax highlighting
pygmentsUseClasses : true
pygmentsCodeFences : true
pygmentsCodefencesGuessSyntax : true

publishDir: "docs"