baseURL : "http://examplesite.com" #copy-paste your domain here
languageCode : "en"
DefaultContentLanguage : "en"
title : "Tutorial Site"
theme : "anatole"
summarylength : 50
enableRobotsTXT : true #leave true for seo
#this file instructs search engine crawlers on how to acess the site

params:
  title : "I'm Jane Doe"
  author : "Jane Doe"
  copyright : "2020-2021"
  description : "Call me Jane"
  profilePicture : "profile.png"
  keywords : "" #seo keywords for your homepage
  #favicons are small images displayed in the browser tab similar to app icons
  favicon : "favicons/" #directory name holding the favicons (relative to the static folder)
  #which folder to use to list posts on the homepage (relative to the content dir)
  mainSections : ["blog"]
  images : ["featured-image.png"]
  doNotLoadAnimations : false
  postSectionName : "blog"
  #uncomment this if you want your site to load in dark-mode by default.
  # displayMode: "dark" 

  ## Social links
  #the icons are loaded from font-awesome library
  #find the icon codes here: https://fontawesome.com/icons?d=gallery&p=2
  # use 'fab' when brand icons, use 'fas' when standard solid icons.
  socialIcons:
    - icon : "fab fa-linkedin"
      title : "Linkedin"
      url : "https://linkedin.com/"
    - icon : "fab fa-github"
      title : "GitHub"
      url : "https://github.com/lxndrblz/anatole/"
    - icon : "fab fa-instagram"
      title : "instagram"
      url : "https://www.instagram.com/"
    - icon : "fas fa-envelope"
      title : "e-mail"
      url : "mailto:mail@example.com"

  # Google Search Console Verification
  #googleSiteVerify : "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  # Read More links for truncated summaries
  # readMore : true

  ## Math settings
  math:
    enable : false  # options: true, false.

## Menu items
menu:
  main:
    - name : "Home"
      identifier : "home"
      weight : 100
      url : "/"
    - name : "Posts"
      weight : 200
      identifier : "posts"
      url : "/blog"
    - name : "About"
      weight : 300
      identifier : "about"
      url : "/about"

taxonomies:
  category: categories
  series: series
  tag: tags

timeout: 30000
#required to exit out of long posts requiring lot of processing.

minify:
  disableXML: true
  minifyOutput: false

# Google Analytics
# Hugo supports GA4 V8.20 (latest at the time of writing) onwards.
#googleAnalytics : "UA-123-45"

publishDir: "docs"